[package]
name = "todo-service-topcoat"
version = "0.1.0"
authors = [
    "Christoph Kappel <christoph@unexist.dev>"
]
license-file = "LICENSE"
homepage = "https://unexist.dev"
repository = "https://hg.unexist.dev/showcase-microservices-rust"
edition = "2024"

[dependencies]
anyhow = "1.0.104"
serde = "1.0.229"
tokio = { version = "1.53.1", features = ["rt-multi-thread", "macros"] }
topcoat = { version = "0.6.2", features = ["router", "tower"] }
dapr = "0.19"
tonic = "0.14.6"
serde_json = "1.0.151"
