[tasks.test]
run = "cargo test -- --test-threads 1 --nocapture"

[tasks.trace]
env.RUST_BACKTRACE = 1
run = "cargo test"

[tasks.build]
raw_args = true
run = "cargo build"

[tasks.clean]
run = "cargo clean"

[tasks.crun]
run = "cargo run"

[tasks.cupgrade]
usage = '''
flag "-d --dry-run" {
    help "Enable dry-running"
}
'''
run = '''
DRY_RUN="${usage_dry_run}"

cargo upgrade -i $DRY_RUN
'''

[tasks.clippy]
run = "bacon clippy"

[tasks.topcoat]
run = "PORT=8080 topcoat dev"

[tasks.dapr_init]
run = "dapr init --container-runtime=podman"

[tasks.dapr_redis]
run = "podman exec -it dapr_redis redis-cli"

[tasks.dapr_stop]
run = "dapr stop"

[tasks.dapr_dash]
run = "diagrid-dev-dashboard"

[tasks.dapr_sidecar]
run = "dapr run --app-id=todo-service --dapr-http-port=3500"

[tasks.dapr_run]
run = "PORT=8080 dapr run --app-id=todo-service --dapr-http-port=3500 -- cargo run"
