[tasks.test]
run = "cargo test -- --test-threads 1 --nocapture"

[tasks.trace]
env.RUST_BACKTRACE = 1
run = "cargo test"

[tasks.build]
raw_args = true
run = "cargo build"

[tasks.clean]
run = "cargo clean"

[tasks.crun]
run = "cargo run"

[tasks.cuc]
usage = '''
flag "-d --dry-run" {
    help "Enable dry-running"
}
'''
run = '''
DRY_RUN=

if [ ${usage_dry_run} ] ; then
    DRY_RUN=-u
fi

cargo update-check $DRY_RUN
'''

[tasks.clippy]
run = "bacon clippy"

[tasks.topcoat]
run = "PORT=8080 topcoat dev"

[tasks.mongo]
run = "podman run -d --rm -p 27017:27017 --name mongodb docker.io/mongo:5"

[tasks.dapr_install]
run = "dapr init --container-runtime=podman"

[tasks.dapr_uninstall]
run = "dapr uninstall"

[tasks.dapr_redis]
run = "podman exec -it dapr_redis redis-cli"

[tasks.dapr_stop]
run = "dapr stop"

[tasks.dapr_dash]
run = "diagrid-dev-dashboard"

[tasks.dapr_sidecar]
run = "dapr run --app-id=todo-service --dapr-http-port=3500"

[tasks.dapr_run]
run = "PORT=8080 dapr run --app-id=todo-service --dapr-http-port=3500 -- cargo run"

[tasks.dapr_res_run]
run = "PORT=8080 dapr run --app-id=todo-service --dapr-grpc-port=5001 --dapr-http-port=3500  --resources-path=statestore/ -- cargo run"

[tasks.dapr_save]
run = "curl -X POST -H 'Content-Type: application/json' -d '[{ \"key\": \"name\", \"value\": \"Bruce Wayne\"}]' http://localhost:3500/v1.0/state/statestore_redis"

[tasks.dapr_retrieve]
run = "curl http://localhost:3500/v1.0/state/statestore_redis/name"
